// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/api-client-proto/api-client.proto

package api_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Yr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Yr) Reset() {
	*x = Yr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_client_proto_api_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Yr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yr) ProtoMessage() {}

func (x *Yr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_client_proto_api_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yr.ProtoReflect.Descriptor instead.
func (*Yr) Descriptor() ([]byte, []int) {
	return file_proto_api_client_proto_api_client_proto_rawDescGZIP(), []int{0}
}

func (x *Yr) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Temp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Temp) Reset() {
	*x = Temp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_client_proto_api_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Temp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temp) ProtoMessage() {}

func (x *Temp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_client_proto_api_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temp.ProtoReflect.Descriptor instead.
func (*Temp) Descriptor() ([]byte, []int) {
	return file_proto_api_client_proto_api_client_proto_rawDescGZIP(), []int{1}
}

func (x *Temp) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_proto_api_client_proto_api_client_proto protoreflect.FileDescriptor

var file_proto_api_client_proto_api_client_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x68, 0x69, 0x6b, 0x61,
	0x2e, 0x63, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x22, 0x1a, 0x0a, 0x02, 0x59, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x1c, 0x0a, 0x04, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x32, 0x46, 0x0a, 0x08, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3a,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x11, 0x2e, 0x63, 0x68, 0x69, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65,
	0x2e, 0x59, 0x72, 0x1a, 0x13, 0x2e, 0x63, 0x68, 0x69, 0x6b, 0x61, 0x2e, 0x63, 0x6c, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x63, 0x68,
	0x69, 0x6b, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x61, 0x70,
	0x69, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_api_client_proto_api_client_proto_rawDescOnce sync.Once
	file_proto_api_client_proto_api_client_proto_rawDescData = file_proto_api_client_proto_api_client_proto_rawDesc
)

func file_proto_api_client_proto_api_client_proto_rawDescGZIP() []byte {
	file_proto_api_client_proto_api_client_proto_rawDescOnce.Do(func() {
		file_proto_api_client_proto_api_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_client_proto_api_client_proto_rawDescData)
	})
	return file_proto_api_client_proto_api_client_proto_rawDescData
}

var file_proto_api_client_proto_api_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_api_client_proto_api_client_proto_goTypes = []interface{}{
	(*Yr)(nil),   // 0: chika.climate.Yr
	(*Temp)(nil), // 1: chika.climate.Temp
}
var file_proto_api_client_proto_api_client_proto_depIdxs = []int32{
	0, // 0: chika.climate.ApiProto.GetTemperature:input_type -> chika.climate.Yr
	1, // 1: chika.climate.ApiProto.GetTemperature:output_type -> chika.climate.Temp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_client_proto_api_client_proto_init() }
func file_proto_api_client_proto_api_client_proto_init() {
	if File_proto_api_client_proto_api_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_client_proto_api_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Yr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_client_proto_api_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Temp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_client_proto_api_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_client_proto_api_client_proto_goTypes,
		DependencyIndexes: file_proto_api_client_proto_api_client_proto_depIdxs,
		MessageInfos:      file_proto_api_client_proto_api_client_proto_msgTypes,
	}.Build()
	File_proto_api_client_proto_api_client_proto = out.File
	file_proto_api_client_proto_api_client_proto_rawDesc = nil
	file_proto_api_client_proto_api_client_proto_goTypes = nil
	file_proto_api_client_proto_api_client_proto_depIdxs = nil
}
